### ISSUE TITLE
git diff 展示工作区和暂存区版本的不同

### ISSUE THREAD

**Issue by ritayzy** [521xueweihan/git-tips#1]
看了博主的技巧，去查看git diff的手册，发现这里好像写错了

![image](https://cloud.githubusercontent.com/assets/18484770/17198992/2da87cf6-54ac-11e6-975a-a596f7a2ad00.png)

这里应该是展示工作区和暂存区版本的不同吧

**Comment by 521xueweihan** [comment]
是的，我写错了，多谢指正。

**Comment by Cyw1104** [comment]
其实这个命令还可以比较 GIT 版本库中任意两个 commit 之间的文件变动
