### ISSUE TITLE
tips（小贴士）称作奇技淫巧是否恰当？

### ISSUE THREAD

**Issue by xuyang2** [521xueweihan/git-tips#22]
貌似 tips 与奇技淫巧两者意思的差别还是比较大。
而且git-tips的内容很多确实只是一些基础操作的小贴士，并没有达到 "diabolic tricks and wicked craft" 的程度。

```
 奇技淫巧 [qí jì yín qiǎo]
    diabolic tricks and wicked craft 
```
```
tips
    N-COUNT A tip is a useful piece of advice. 建议 
    n. 秘诀，技巧；小贴士，小窍门
```

**Comment by kasuganosoras** [comment]
中华文化博大精深，没必要钻字眼，一字一句去翻译，起个大家都看得懂的名字就好了
比如我自称鸽子王，翻译为英文就是 Pigeon King，啥玩意……
（逃

**Comment by 521xueweihan** [comment]
@xuyang2 项目名称并未按照 tips 的原意翻译，只是取了个“意”。
