### ISSUE TITLE
Github 现在支持私人仓库

### ISSUE THREAD

**Issue by alfredchan3** [521xueweihan/git-tips#26]
Github 现在支持最多 3 个协作者的私人仓库，“免费的只能 public” 下面 可以加一条 ，支持“最多 3 个协作者以下的 Private Repo”。

**Comment by 521xueweihan** [comment]
具体描述方便截图翻一下吗？我没找到。。。

**Comment by alfredchan3** [comment]
![1](https://user-images.githubusercontent.com/13319109/56345098-87828000-61f1-11e9-93dc-dac690b56fcd.PNG)

**Comment by 521xueweihan** [comment]
@alfredchan3 感谢，收到。已联系图解贡献者。有序进展会在本 issues 中回复。

**Comment by zzugbb** [comment]
![image](https://user-images.githubusercontent.com/31366103/56350422-5445ee00-61fd-11e9-935e-476f6cada669.png)

@alfredchan3 @521xueweihan   如上图所见，已修正（补充了描述）

**Comment by 521xueweihan** [comment]
@alfredchan3 @zzugbb 已合并PR，问题修复。感谢各位
