### ISSUE TITLE
增加远程仓库 的问题

### ISSUE THREAD

**Issue by Cyw1104** [521xueweihan/git-tips#3]
文中 `增加远程仓库` 给出的指令是：

```
  git remote add origin <remote-url>
```

这里的 `origin`  可以是任意的名称，如果库是从远程 `clone` 到本地的话，默认的远程库名称是 `origin`，
正确的指令是：

```
 git remote add <name>  <remote-url>
```

参见： [git-remote](https://git-scm.com/docs/git-remote)

**Comment by 521xueweihan** [comment]
关于增加远程仓库的问题，是为了统一问中所有的远程仓库的名称，所以这里名字写成‘origin’。非常感谢指出文中的错误，另外两个错误我已经修改完：https://github.com/521xueweihan/git-tips/commit/9fb7994db9fb73389eb89129bfde8a54be10e42a

**Comment by Cyw1104** [comment]
没事，我也学到了不少东西，感谢你能够整理知识
