### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by mayben0t** [521xueweihan/git-tips#44]
是这样的，远程有个test分支，但是被人删了 ，然后他重新推了个test分支到远端
这种情况下 能查出是谁这么干的吗。。

**Comment by 521xueweihan** [comment]
这个要去网页（github、gitlab）上看 event

**Comment by mayben0t** [comment]
> 这个要去网页（github、gitlab）上看 event

谢谢 看到了 但是有点乱。。
