### ISSUE TITLE
建议把这些命令分门别类一下

### ISSUE THREAD

**Issue by sheldonshen** [521xueweihan/git-tips#5]
https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

**Comment by 521xueweihan** [comment]
@sheldonshen  感谢提供这么好的建议。

我觉得：

1. 由于 git-tips 命令数量过多，不易于分类
2. 同时分类后并不会增加查询的速度
3. 关于索引可以通过浏览器中的 **页面查找** （cmd＋f）

GitHub 的 git-cheat-sheet 我认为写的非常好，后面可以单开个项目进行翻译，排版。做成 查询手册的模式（精简版的 git-tips）

欢迎继续讨论 😁
